### ISSUE TITLE
Internal Review Feedback

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/anti-slavery-manuscripts#142]
## Internal Review
Compiled from the Slack `#project-review` channel on Fri 3 Nov 14:30 (UK time). Special thanks to everyone who took time on a Friday afternoon to help test the project.

### Major Issues
- [x] Tutorial not displayed
  - [ ] Tutorial needs a rewrite - right now it's only for the A-split
  - [ ] Tutorial images are too damn big
  - [ ] Do we need separate workflows for the A/B split?
- [x] Data is being posted to CAESAR STAGING on PRODUCTION. (See #143)
- [x] When a user makes Annotations on Subject A, then navigates away from the Classifier page, then returns, they will see Subject B loading, but with Subject A's Annotations.
- [ ] Is the 'slavery' in antislaverymanuscripts.org preventing users on certain networks from accessing the website?

### Logic Issues
- [x] _The filmstrip remembers the previous subject's page I was view after loading a new subject (i.e. is skipped right to page 4 of a new subject when I clicked done)_ (See #145) 
- [x] Special edge case: `[deletion] [unclear] [/deletion]` should be one word. Note the spaces auto-inserted around `[unclear]`. (See #145) 

### Accessibility
- [ ] Can we use the keyboard to navigate the subject image?
  - [ ] What about a virtual cursor?
- [x] Investigate tab navigation (See #155)
  - [x] Do we clearly indicate which element has focus?
  - [x] Transcription dialog's text input should capture focus as soon as the transcription modal is opened.

### UI/UX Issues & Improvements
- [x] Consider mouse cursors being used in annotation mode - perhaps use crosshairs? (See #147 )
- [x] Top level navi seems weird - it's not styled properly (hover state, font) and navigates users out of the project (i.e., it's not _blank )
- [x] It's too easy to accidentally start a new annotation by, e.g., mis-clicking the 'expand dialog' button. (See #147 )
- [x] Change the "Done" button (which opens the Submit Classification Form, which in turn has "Done" and "Done & Talk") to "Finish" or "Finished". Let's not repeat ourselves. (See #147 )

### Uncategorised
- [x] liberating-the-liberator repo should be renamed anti-slavery-manuscripts
- [ ] Check with back-end team to remove the "oAuth pls authorise this app" step from the login process.

**Comment by simoneduca** [comment]
Remove redux-logger from production.

**Comment by CKrawczyk** [comment]
Production is connecting to caesar-staging.zooniverse.org instead of caesar.zooniverse.org

**Comment by srallen** [comment]
The annotation modal isn't a true modal by design to allow users to interact with the zooming tools, however, you can accidentally start another annotation.

Suggestion: Use a `<textarea />` instead of a `<input type="text" />` so the input expands using normal browser behavior. In slack chat, it was noted that the vertical expansion might encourage users to transcribe multiple lines, but this might be prevented by setting `row="1"` and `"wrap="off"` (see supported attributes: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea).

**Comment by srallen** [comment]
The links on the home page do not have hover states.

**Comment by simoneduca** [comment]
It looks like a session is reset every time a page reloads, which is not how sessions work and it isn't great for tracking session in the backend.

**Comment by snblickhan** [comment]
Autofocus the text box

**Comment by eatyourgreens** [comment]
Keyboard controls for pan/zoom, while transcribing, would be useful.

**Comment by eatyourgreens** [comment]
@simoneduca that's the [session ID code from PFE](/zooniverse/Panoptes-Front-End/blob/master/app/lib/session.coffee#L15), which generates a new session ID after 5 minutes of inactivity.

I think the assumption in the PFE code is that `getSessionID()` will be called repeatedly during a session, to keep the current sessionID active. It doesn't reset the session ID on page load, though, it reads it from `sessionStorage` and resets if it's more than 5 minutes old.

**Comment by beckyrother** [comment]
Cross-posting this design issue: https://github.com/zooniverse/anti-slavery-manuscripts/issues/133

**Comment by beckyrother** [comment]
## Additional UI/UX issues
-When the transcription box is active the mouse should allow the user to pan around the image but not create new annotations
-Within the classify page, About and Talk are not capitalize in the top Nav
-Don't show an error message while the user is typing their transcription, wait till they click Done: 
![anti-slavery_manuscripts](https://user-images.githubusercontent.com/1392130/32388713-8d25cf1a-c096-11e7-9183-7ed1505f32f8.png)

**Comment by snblickhan** [comment]
To add to the UX list: allow users to edit dot placement (click & drag) after the fact. Not a requisite for beta, but something to do if we have time.

**Comment by eatyourgreens** [comment]
A really small thing: `<button href="#">` appears in [a few places in the code](/zooniverse/anti-slavery-manuscripts/blob/61d021895a0df369361c726745df451a7b446279/src/containers/ClassifierContainer.jsx#L114), but is not valid HTML. `href` is used on links, not buttons, and should be deleted here.

**Comment by snblickhan** [comment]
As of today, the tutorial isn't popping up when new users (who are logged in) come to the ASM site. I know that this was spotted last Friday during internal testing and was supposedly fixed, but just flagging up that it's still happening.

**Comment by beckyrother** [comment]
### Expert feedback
Walked through the interface with the gold standard researcher this morning and she brought up some good points:
- [ ] Clicking "reset image" does not reset the negative (`Contrast`) button
- [ ] Need to add a section in the Field Guide about punctuation, specifically comma and double-comma usage, and em dashes and hyphens.
- [ ] Adding multiple modifiers affects the word count.
- [ ] It's possible to create transcriptions at 90º, which I don't think should be an option.

**Comment by wgranger** [comment]
I think we should allow users to create transcriptions at 90º, especially in the case of cross-writing.

**Comment by snblickhan** [comment]
I initially had the same thought as @wgranger but I think this might refer to transcriptions _which are perpendicular to the direction of the text_, not transcriptions which are made _when the page is rotated to 90º_

@beckyrother please correct me if I'm wrong.

**Comment by beckyrother** [comment]
Sorry that wasn't clear. I'm referring to the ability to create annotations which are at 90º : 
![anti-slavery_manuscripts](https://user-images.githubusercontent.com/1392130/32746684-0313dac2-c87c-11e7-87e6-882275841ce1.png)

Open to suggestions but I'm not sure this will produce optimal results as it's quite difficult to read script that's sideways.

**Comment by snblickhan** [comment]
Yes, I think that's a good call, as it will require users to rotate the page to transcribe.

**Comment by snblickhan** [comment]
>  Need to add a section in the Field Guide about punctuation, specifically comma and double-comma usage, and em dashes and hyphens.

This would be great, but the content will need to be generated from BPL. Did they offer to create that content, or were they assuming we'd do it? If so, I can email Tom to ask him if they'll do it. In either case, probably not a priority for beta (but will still be v good to have!).

**Comment by beckyrother** [comment]
Re field guide, we didn't really talk about who would be responsible for that content. I told them we'd email with more guidance around how other projects treat punctuation like em dashes and double commas, and also when the gold standard toggle button was ready ( @wgranger ). Might be good to address all that at once

**Comment by wgranger** [comment]
I'm closing this issue as most of the items has been covered, and any other issues are replicated in newer items.
