### ISSUE TITLE
Full Launch Checklist

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/anti-slavery-manuscripts#223]
Note: Aiming for full launch on 23 January (for National Handwriting Day)
- [x] Unlink subjects over 10pp long
- [x] Chronological subject set rollout (start with 1800-1839)
- [x] Update banner to note that Beta 2 has ended:
> Thanks for participating in our beta review! We're making some changes based on your feedback, and will be launching the full project soon!
- [x] Daily Zoo post for full launch (SB)
- [ ] Continue to watch open issues: #216 #218(#226) #220 
- [x] Tutorial updates to reflect beta feedback (SB)
- [x] Field Guide updates (SB + BPL team)
- [x] Remove traces of beta testing (ex. Initial popup reminder to sign in mentioning "beta test") #225

**Comment by wgranger** [comment]
@beckyrother For the chronological subject set, are we going to keep the UI the same on the landing page (with "Start Transcribing") with 1800-1839 linked? I'm thinking that in lieu of subject set selection we originally had.

@snblickhan We've had some convo in the past couple days about stats, but did we decide for sure on the project navbar link to "stats" as opposed to "feedback"? See #221

**Comment by snblickhan** [comment]
@wgranger Yes -- we won't have a feedback link any longer, so it can become Stats.

**Comment by beckyrother** [comment]
Yes, since it sounds like we're rolling the subject sets out one at a time, “Start Transcribing” should just go to that first subject set. Once additional subject sets have been added, we can implement that additional UI with links to different time periods. Does that make sense, @snblickhan?

**Comment by wgranger** [comment]
We should be all set with the items covered on this list.
